machine_list = [
    # busy
    ["visiongpu51.csail.mit.edu", 0, ],
    ["visiongpu51.csail.mit.edu", 1, ],
    ["visiongpu51.csail.mit.edu", 2, ],
    ["visiongpu51.csail.mit.edu", 3, ],
    ["visiongpu51.csail.mit.edu", 4, ],
    ["visiongpu51.csail.mit.edu", 5, ],
    ["visiongpu51.csail.mit.edu", 6, ],
    ["visiongpu51.csail.mit.edu", 7, ],
    ["visiongpu52.csail.mit.edu", 0, ],
    ["visiongpu52.csail.mit.edu", 1, ],
    ["visiongpu52.csail.mit.edu", 2, ],
    ["visiongpu52.csail.mit.edu", 3, ],
    ["visiongpu52.csail.mit.edu", 4, ],
    ["visiongpu52.csail.mit.edu", 5, ],
    ["visiongpu52.csail.mit.edu", 6, ],
    ["visiongpu52.csail.mit.edu", 7, ],
    ["visiongpu53.csail.mit.edu", 0, ],
    ["visiongpu53.csail.mit.edu", 1, ],
    ["visiongpu53.csail.mit.edu", 2, ],
    ["visiongpu53.csail.mit.edu", 3, ],
    ["visiongpu53.csail.mit.edu", 4, ],
    ["visiongpu53.csail.mit.edu", 5, ],
    # ["visiongpu53.csail.mit.edu", 6, ],
    # ["visiongpu53.csail.mit.edu", 7, ],
    ["visiongpu54.csail.mit.edu", 0, ],
    ["visiongpu54.csail.mit.edu", 1, ],
    ["visiongpu54.csail.mit.edu", 2, ],
    ["visiongpu54.csail.mit.edu", 3, ],
    ["visiongpu54.csail.mit.edu", 4, ],
    ["visiongpu54.csail.mit.edu", 5, ],
    ["visiongpu54.csail.mit.edu", 6, ],
    ["visiongpu54.csail.mit.edu", 7, ],
    ["visiongpu55.csail.mit.edu", 0, ],
    ["visiongpu55.csail.mit.edu", 1, ],
    ["visiongpu55.csail.mit.edu", 2, ],
    # ["visiongpu55.csail.mit.edu", 3, ],
    # ["karhu.csail.mit.edu", 0, ],
    # ["karhu.csail.mit.edu", 1, ],
    # # ["karhu.csail.mit.edu", 2, ],
    # ["karhu.csail.mit.edu", 3, ],
]
